---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create DB for service
  mysql_db:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ horizon_galera_address }}"
    name: "{{ horizon_galera_database }}"
    state: "present"
  delegate_to: "{{ horizon_db_setup_host }}"
  no_log: True

- name: Grant access to the DB for the service
  mysql_user:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ horizon_galera_address }}"
    name: "{{ horizon_galera_user }}"
    password: "{{ horizon_container_mysql_password }}"
    host: "{{ item }}"
    state: "present"
    priv: "{{ horizon_galera_database }}.*:ALL"
  delegate_to: "{{ horizon_db_setup_host }}"
  with_items:
    - "localhost"
    - "%"
  no_log: True

- name: Perform a horizon DB sync
  command: "{{ horizon_manage }} migrate --noinput"
  become: yes
  become_user: "{{ horizon_system_user_name }}"
  changed_when: false

- name: Register DB session cleanup cron
  cron:
    name: "Clear out expired sessions"
    minute: "{{ 58 | random(seed=inventory_hostname, start=2) }}"
    hour: 21
    job: "{{ horizon_manage }} clearsessions"
    user: "{{ horizon_system_user_name }}"
    state: present
